SRC +=    src/base/abci/abc.c \
    src/base/abci/abcAttach.c \
    src/base/abci/abcAuto.c \
    src/base/abci/abcBalance.c \
    src/base/abci/abcBidec.c \
    src/base/abci/abcBm.c \
    src/base/abci/abcBmc.c \
    src/base/abci/abcCas.c \
    src/base/abci/abcCascade.c \
    src/base/abci/abcCollapse.c \
    src/base/abci/abcCut.c \
    src/base/abci/abcDar.c \
    src/base/abci/abcDebug.c \
    src/base/abci/abcDec.c \
    src/base/abci/abcDetect.c \
    src/base/abci/abcDress.c \
    src/base/abci/abcDress2.c \
    src/base/abci/abcDress3.c \
    src/base/abci/abcDsd.c \
    src/base/abci/abcEco.c \
    src/base/abci/abcExact.c \
    src/base/abci/abcExtract.c \
    src/base/abci/abcFraig.c \
    src/base/abci/abcFx.c \
    src/base/abci/abcFxu.c \
    src/base/abci/abcGen.c \
    src/base/abci/abcHaig.c \
    src/base/abci/abcIf.c \
    src/base/abci/abcIfif.c \
    src/base/abci/abcIfMux.c \
    src/base/abci/abcIvy.c \
    src/base/abci/abcLog.c \
    src/base/abci/abcLut.c \
    src/base/abci/abcLutmin.c \
    src/base/abci/abcMap.c \
    src/base/abci/abcMerge.c \
    src/base/abci/abcMfs.c \
    src/base/abci/abcMini.c \
    src/base/abci/abcMiter.c \
    src/base/abci/abcMulti.c \
    src/base/abci/abcNtbdd.c \
    src/base/abci/abcNpn.c \
    src/base/abci/abcNpnSave.c \
    src/base/abci/abcOrchestration.c \
    src/base/abci/abcOdc.c \
    src/base/abci/abcOrder.c \
    src/base/abci/abcPart.c \
    src/base/abci/abcPrint.c \
    src/base/abci/abcProve.c \
    src/base/abci/abcQbf.c \
    src/base/abci/abcQuant.c \
    src/base/abci/abcRec3.c \
    src/base/abci/abcReconv.c \
    src/base/abci/abcReach.c \
    src/base/abci/abcRefactor.c \
    src/base/abci/abcRenode.c \
    src/base/abci/abcReorder.c \
    src/base/abci/abcRestruct.c \
    src/base/abci/abcResub.c \
    src/base/abci/abcRewrite.c \
    src/base/abci/abcRpo.c \
    src/base/abci/abcRr.c \
    src/base/abci/abcRunGen.c \
    src/base/abci/abcSat.c \
    src/base/abci/abcSaucy.c \
    src/base/abci/abcScorr.c \
    src/base/abci/abcSense.c \
    src/base/abci/abcSpeedup.c \
    src/base/abci/abcStmap_0.c \
    src/base/abci/abcStmap_1.c \
    src/base/abci/abcStmap_2.c \
    src/base/abci/abcStmap_3.c \
    src/base/abci/abcStmap_4.c \
    src/base/abci/abcStmap_5.c \
    src/base/abci/abcStmap_6.c \
    src/base/abci/abcStmap_7.c \
    src/base/abci/abcStmap_8.c \
    src/base/abci/abcStmap_9.c \
    src/base/abci/abcStmap_10.c \
    src/base/abci/abcStmap_11.c \
    src/base/abci/abcStmap_12.c \
    src/base/abci/abcStmap_13.c \
    src/base/abci/abcStmap_14.c \
    src/base/abci/abcStmap_15.c \
    src/base/abci/abcStmap_16.c \
    src/base/abci/abcStmap_17.c \
    src/base/abci/abcStmap_18.c \
    src/base/abci/abcStmap_19.c \
    src/base/abci/abcStmap_20.c \
    src/base/abci/abcStmap_21.c \
    src/base/abci/abcStmap_22.c \
    src/base/abci/abcStmap_23.c \
    src/base/abci/abcStmap_24.c \
    src/base/abci/abcStmap_25.c \
    src/base/abci/abcStmap_26.c \
    src/base/abci/abcStmap_27.c \
    src/base/abci/abcStmap_28.c \
    src/base/abci/abcStmap_29.c \
    src/base/abci/abcStmap_30.c \
    src/base/abci/abcStmap_31.c \
    src/base/abci/abcStmap_32.c \
    src/base/abci/abcStmap_33.c \
    src/base/abci/abcStmap_34.c \
    src/base/abci/abcStmap_35.c \
    src/base/abci/abcStmap_36.c \
    src/base/abci/abcStmap_37.c \
    src/base/abci/abcStmap_38.c \
    src/base/abci/abcStmap_39.c \
    src/base/abci/abcStmap_40.c \
    src/base/abci/abcStmap_41.c \
    src/base/abci/abcStmap_42.c \
    src/base/abci/abcStmap_43.c \
    src/base/abci/abcStmap_44.c \
    src/base/abci/abcStmap_45.c \
    src/base/abci/abcStmap_46.c \
    src/base/abci/abcStmap_47.c \
    src/base/abci/abcStmap_48.c \
    src/base/abci/abcStmap_49.c \
    src/base/abci/abcStmap_50.c \
    src/base/abci/abcStmap_51.c \
    src/base/abci/abcStmap_52.c \
    src/base/abci/abcStmap_53.c \
    src/base/abci/abcStmap_54.c \
    src/base/abci/abcStmap_55.c \
    src/base/abci/abcStmap_56.c \
    src/base/abci/abcStmap_57.c \
    src/base/abci/abcStmap_58.c \
    src/base/abci/abcStmap_59.c \
    src/base/abci/abcStmap_60.c \
    src/base/abci/abcStmap_61.c \
    src/base/abci/abcStmap_62.c \
    src/base/abci/abcStmap_63.c \
    src/base/abci/abcStrash.c \
    src/base/abci/abcSweep.c \
    src/base/abci/abcSymm.c \
    src/base/abci/abcTim.c \
    src/base/abci/abcTiming.c \
    src/base/abci/abcTopo.c \
    src/base/abci/abcUnate.c \
    src/base/abci/abcUnreach.c \
    src/base/abci/abcVerify.c \
    src/base/abci/abcXsim.c 
